### ISSUE TITLE
Opting to omit InventoryHolder in InventoryGui constructor causes NPE

### ISSUE THREAD

**Issue by simpleauthority** [Phoenix616/InventoryGui#1]
See stack trace: https://hastebin.com/fihumivobo.css
Caused by this code: https://hastebin.com/usihoyisir.java

Which depends on: https://hastebin.com/obixoyatet.java

Setting the gui owner solves the issue:
```
        PlayerInfoGui gui = plugin.getGuiManager().getPlayerInfoGui(request.getWhoToShow());
        plugin.getLogger().info("gui is null? " + (gui == null));
        if (gui == null) return;
        gui.setOwner(showTo);

        gui.show(showTo);
```

**Comment by simpleauthority** [comment]
@Phoenix616

**Comment by Phoenix616** [comment]
Unfortunately I'm not in a position where I can look into such issues properly right now as indicated on spigot.

I suggest to make sure that you actually use the latest version as such an issue was fixed recently. Also please directly include logs in the issue/gist as your pastes seem to have been removed already.

**Comment by Phoenix616** [comment]
Apparently hastebin just had some issues and shows the paste again but as I said before: Make sure you are actually running the latest version, your stack trace even points to a line ([767](https://github.com/Phoenix616/InventoryGui/blob/master/src/main/java/de/themoep/inventorygui/InventoryGui.java#L767)) which isn't even in the method that is supposed to cause it (replaceVars) anymore.

**Comment by simpleauthority** [comment]
My bad. You're right. Sorry my dude.
