### ISSUE TITLE
Issue with maven dependency

### ISSUE THREAD

**Issue by CDFN** [Phoenix616/InventoryGui#11]
Gradle couldn't import dependency. I think it may be caused by redirect from https://repo.minebench.de/ to https://repo.phoenix616.dev/. After changing repository URL it worked. Also Maven import example in documentation has 1.4.1-SNAPSHOT version instead of latest (1.4.2-SNAPSHOT).

**Comment by Phoenix616** [comment]
It uses a standard temporary http redirect (as it will be moved back to the normal url) which works without issues in maven. If it doesn't in gradle then I suggest reporting that bug to them.
