### ISSUE TITLE
InventoryGui Issue while loading the plugin.

### ISSUE THREAD

**Issue by FakeSnakeAmazing** [Phoenix616/InventoryGui#13]
Hello Phoenix,
I don't know if this is the appropriate way to contact with you, but I dind't find another.
So, I'm having an issue while trying to use your library to create a GUI for my plugin. Probably is an idiot issue, but I'm a new dev and I'm still learning how to develop. If you have time, here I send you my issue.

https://hastebin.com/ituxejulab.cs

Thanks :)

**Comment by Phoenix616** [comment]
Did you shade it into your plugin like instructed in the readme? Also you might want to relocate it into your plugin's own package to ensure that it can't conflict with other plugins using it.

**Comment by SnakeAmazing** [comment]
I'm not sure of what do you mean with shading it into my plugin. I have read the readme and created the gui as the example for understanding the gui better but didn't work, here you have my code.

https://hastebin.com/ecewemoyay.java

**Comment by Phoenix616** [comment]
The readme links [an example](https://github.com/Minebench/Pipes/blob/048337e7594684353e7360411b1ef6ba8e7223c4/pom.xml#L63-L82) of how to shade and relocate it into your own package. If you already do that then feel free to share your pom here.

**Comment by SnakeAmazing** [comment]
Okay, I didn't do that, but still dosn't work. here is my pom https://hastebin.com/ifixupolar.xml

**Comment by Phoenix616** [comment]
Well first off: You don't relocate into your own package but into the one from the example plugin. It looks correct though, I suggest checking your jar file if the missing class is in there and if not figure out why maven isn't adding it.

**Comment by SnakeAmazing** [comment]
Sorry, im still learning maven and java. I have changed pattern to me.snakeamazing and i don't know what i should put into shadedpattern. my main class? https://hastebin.com/ikumipugib.xml

**Comment by Phoenix616** [comment]
I suggest reading up on it then. The pattern is the class path of the classes that you want to relocate (the one from the library), the shadedPattern is the one where you want to move it to while shading.

**Comment by SnakeAmazing** [comment]
Okay, I figured out how to do that. Now the plugin is working but when I type the command the GUI doesn't appear. I think it's because I haven't add the lines InventoryGui gui =  InventoryGui.get(InventoryHolder holder); and gui.show(player); because when I try to add it it shows me an error that the var is repeated. Obviuously is repeted because i have the var before. I have tryed doing this```
         gui = InventoryGui.get(InventoryHolder p);
        gui.show(p);
``` but doesn't work to, because in (InventoryHolder p) tells me that before p is expected ; or )

I don't know if my explanation was good, sorry for my english

**Comment by Phoenix616** [comment]
Just use your gui variable directly, the InventoryGui#get(InventoryHolder) method is to get a GUI that was created somewhere else from the holder (e.g. when its bound directly to a container block).

And the error it shows you is due to not using correct java syntax but the doc syntax.

**Comment by SnakeAmazing** [comment]
Okay, I have solved it. Thanks for support
