### ISSUE TITLE
interact with player's inventory

### ISSUE THREAD

**Issue by weihao** [Phoenix616/InventoryGui#18]
#### Is your feature request related to a problem? Please describe.

N/A

#### Describe the solution you'd like

Add functionality to support click events when the player clicked on player inventory.

**Comment by weihao** [comment]
After reading the code, I have found a way to achieve this without modifying the code.

I needed the `Inventory` for the InventoryClickEvent listener to check for the same inventory, and I was able to get by creating a new Holder and access it there. 
```
Inventory inv = new InventoryGui.Holder(gui).getInventory();
```
![gui](https://user-images.githubusercontent.com/31719556/104283041-f13ec500-547d-11eb-9c0b-9f0b6e2c7d15.png)


We have to create a holder because `getInventory()` method is only public in the Holder class. **I think this could be improved to allow extensive use of the library**, for example, allow players to put items in the GUI.

**Comment by Phoenix616** [comment]
Well the plugin is meant to handle a custom GUI with elements at the top of the inventory view, not elements in the player inventory hence it does not support showing elements there and I personally don't think that ti should be as it would make things a lot more complex than it is right now.

But If all you want to do is allow items to be put into the GUI from the player inventory then you can use the [GuiStorageElement](https://wiki.phoenix616.dev/library:inventorygui:usage#storage-element) which is designed for exactly that purpose.

**Comment by weihao** [comment]
It is not obvious that `GuiStorageElement` can allow item as input, could you show an example?

From my understanding that gui storage current only renders the item and cannot assign any action to it.

**Comment by Phoenix616** [comment]
You don't need to assign any actions to it. They behave the exact same way as a slot in a normal chest or other container (putting the item into the backing Inventory directly with the normal Vanilla action). If you want to do something special while the player is clicking on a slot with an item on their cursor then any of the other element types will work. Of course you can always just implement your own GuiElement extending class.

**Comment by weihao** [comment]
Got it, thanks!

I noticed that if I reload the server, the inventory click handler will not work. so if a player has the menu open when the server reloads, the player is able to take out items from the gui because the events are not canceled.

Is this an expected behavior in the library? When I implemented my gui, I will iterate through all the opened inventory and just close them.

**Comment by weihao** [comment]
The player cannot place any item in the GUI created by the example code. Am I missing something here?

```
        Inventory inv = Bukkit.createInventory(null, InventoryType.CHEST);
        getGui().addElement(new GuiStorageElement('i', inv));
```

```
                "iiiiiiiii",
                "iiiiiiiii",
                "iiiiiiiii",
                "iiiiiiiii",
                "iiiiiiiii",
                "p       n",
````

**Comment by Phoenix616** [comment]
> Got it, thanks!
> 
> I noticed that if I reload the server, the inventory click handler will not work. so if a player has the menu open when the server reloads, the player is able to take out items from the gui because the events are not canceled.
> 
> Is this an expected behavior in the library? When I implemented my gui, I will iterate through all the opened inventory and just close them.

I don't use reloads for multiple reasons so I never think about those. (As they tend to break tons of stuff) Please open a separate issue regarding that and I look into that. Persisting GUI functionality beyond plugin disable and enable will most likely not work though. And in the current state it would be best to just close all GUIs on plugin disable if you want to support reloads.



> The player cannot place any item in the GUI created by the example code. Am I missing something here?
> 
> ```
>         Inventory inv = Bukkit.createInventory(null, InventoryType.CHEST);
>         getGui().addElement(new GuiStorageElement('i', inv));
> ```
> 
> ```
>                 "iiiiiiiii",
>                 "iiiiiiiii",
>                 "iiiiiiiii",
>                 "iiiiiiiii",
>                 "iiiiiiiii",
>                 "p       n",
> ```

What exactly do you mean by "cannot place any item in the GUI"? Does it cancel the interaction or does it not save the placed items? Please also make sure you aren't trying to place in a slot which is outside the backing inventory's size. (Chests have only 27 slots)

**Comment by weihao** [comment]
> > Got it, thanks!
> > I noticed that if I reload the server, the inventory click handler will not work. so if a player has the menu open when the server reloads, the player is able to take out items from the gui because the events are not canceled.
> > Is this an expected behavior in the library? When I implemented my gui, I will iterate through all the opened inventory and just close them.
> 
> I don't use reloads for multiple reasons so I never think about those. (As they tend to break tons of stuff) Please open a separate issue regarding that and I look into that. Persisting GUI functionality beyond plugin disable and enable will most likely not work though. And in the current state it would be best to just close all GUIs on plugin disable if you want to support reloads.
> 
> > The player cannot place any item in the GUI created by the example code. Am I missing something here?
> > ```
> >         Inventory inv = Bukkit.createInventory(null, InventoryType.CHEST);
> >         getGui().addElement(new GuiStorageElement('i', inv));
> > ```
> > 
> > 
> > ```
> >                 "iiiiiiiii",
> >                 "iiiiiiiii",
> >                 "iiiiiiiii",
> >                 "iiiiiiiii",
> >                 "iiiiiiiii",
> >                 "p       n",
> > ```
> 
> What exactly do you mean by "cannot place any item in the GUI"? Does it cancel the interaction or does it not save the placed items? Please also make sure you aren't trying to place in a slot which is outside the backing inventory's size. (Chests have only 27 slots)

![example](https://imgur.com/hCLfIue.gif)
What I want to achieve is placing an item from the player's inventory in the chest GUI. It did not work as expected.

**Comment by Phoenix616** [comment]
It works when I test it with a virtual inventory backing it. Can you share a more complete version of the code you are using? (Also please make sure you don't have some other plugin blocking the interaction)

**Comment by weihao** [comment]
Solved 😄
