### ISSUE TITLE
Fallback for server reload

### ISSUE THREAD

**Issue by weihao** [Phoenix616/InventoryGui#20]
The library needs to close all the opened inventory on disabling, otherwise, it would be a duplication glitch. Many do use reload and some may accidentally run reload, so the library needs to support this functionality.

---
I noticed that if I reload the server, the inventory click handler will not work. so if a player has the menu open when the server reloads, the player is able to take out items from the gui because the events are not canceled.

Is this an expected behavior in the library? When I implemented my gui lib, I will iterate through all the opened inventory and just close them.

_Originally posted by @weihao in https://github.com/Phoenix616/InventoryGui/issues/18#issuecomment-759353005_

**Comment by weihao** [comment]
Plugins that heavily use static will run into issues with a reload, but if a plugin is implemented initialization and destroy correctly it should work flawlessly.

**Comment by weihao** [comment]
@Phoenix616, A server reload will still leave any inventory open, so I think you should close player inventory before destruction.
``` 
           for (Player player : Bukkit.getOnlinePlayers()) {
                if (player has inventorygui created gui open) {
                    player.closeInventory();
                }
            }
```

**Comment by Phoenix616** [comment]
The destroy method [already closes](https://github.com/Phoenix616/InventoryGui/blob/master/src/main/java/de/themoep/inventorygui/InventoryGui.java#L607) all open GUIs.
