### ISSUE TITLE
Latest version caused bugs

### ISSUE THREAD

**Issue by weihao** [Phoenix616/InventoryGui#24]
#### Used Version

 9ad5463680
 ```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
	<dependency>
	    <groupId>com.github.Phoenix616</groupId>
	    <artifactId>InventoryGui</artifactId>
	    <version>9ad5463680</version>
	</dependency>
```

My code breaks when I use the latest version. Is there any testing before you pushed the code to master?

**Comment by Phoenix616** [comment]
Well what exactly are you doing and what breaks? It definitely doesn't cause the GUI to break completely but of course there might be issues with certain element combinations/use cases.

**Comment by weihao** [comment]
Use case: https://github.com/weihao/itemraffle/blob/main/src/main/java/org/akadia/itemraffle/guis/DepositoryListCommonMenu.java#L21-L60

When I am using 1.4.2-SNAPSHOT, the dynamic gui re-draw works fine.

When I upgraded to the latest version, the code breaks.
