### ISSUE TITLE
Option to show inventory with custom replacements

### ISSUE THREAD

**Issue by P3ridot** [Phoenix616/InventoryGui#29]
I don't know if it possible to add (at least in an easy way) but option to show inventory with custom replacements would be great. Unfortunately it would require creating new inventory (bukkit inventory) every showing inventory but I think developers 
who would use it should care about performance.

**Comment by Phoenix616** [comment]
I'm unsure what you mean by that? Replacements in the title of the view?

**Comment by P3ridot** [comment]
Yeah

**Comment by Phoenix616** [comment]
Well I have been simply replacing them when creating the InventoryGui object if I wanted the GUI to be different per player. (Per player elements were an afterthought too, re-using GUIs that are different per player wasn't really the goal)

**Comment by P3ridot** [comment]
I have to create multilingual inventory (with other title for every language) so I guess I will just create map with inventory for every language and use it.
