### ISSUE TITLE
Per-player element

### ISSUE THREAD

**Issue by Proximyst** [Phoenix616/InventoryGui#3]
Having a per-player element (e.g. one which lets you say `fish` to Lax, but `You're gold!` to any other player) would quickly cut down on amount of times a GUI would have to be made in a single plugin if it has different behaviour per player.

I'd simply suggest a type such as `PlayerDynamicElement(char setupSubstitution, Function<Player, StaticGuiElement> element)`.

**Comment by Phoenix616** [comment]
Some thoughts about this:

Currently one InventoryGui instance only really corresponds to one player having them open with the inventory being cached in a field of the object. This would probably need to be changed into a map for all players to properly handle the listeners (as they too use the cached inventory: to check if the player is actually in the GUI)

We would also need to pass the player to all methods for getting items and actions from all element types (which would end up in quite some clutter imo) or add a special case for such a per-player element. (Which I also don't think is a nice approach but already kinda used with the storage element)

A different approach could be to calculate an intermediate GUI setup for each player that opens the GUI which resolves the player elements but that too would require a special case for these elements to work...

Have to think about this a bit more, if you (or anyone else) have any thoughts on this feel free to provide them! :)

**Comment by Phoenix616** [comment]
It is now (since 1.4) possible to provide a Function to DynamicGuiElement which has the viewer as the input. Also the getItem and getAction methods now take the viewer too if one wants to implement custom elements.
