### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Technosword** [Phoenix616/InventoryGui#32]
Hey! Just wanted to let you know that this should technically be licensed under a GNU Public License (GPL) v3 license. This is because Bukkit is under this license and you're using their API. I suggest you change it, thanks!

**Comment by Phoenix616** [comment]
The project is already licensed under a GPL compatible one (a MIT license, see [the license file](https://github.com/Phoenix616/InventoryGui/blob/master/LICENSE)).
