### ISSUE TITLE
Left / right click check

### ISSUE THREAD

**Issue by stijnb1234** [Phoenix616/InventoryGui#43]
It would be great if it's possible to detect if a click interaction was a left or a right click. This way, both clicks can have different actions.
Probably depends on #38 to be fixed first.

Workaround until this is implemented:
```java
if (!(action.getRawEvent() instanceof InventoryClickEvent)) return;
InventoryClickEvent event = (InventoryClickEvent) action.getRawEvent();
if (event.getClick() == ClickType.LEFT) {
     //This was a left click
} else if (event.getClick() == ClickType.RIGHT) {
     //This was a right click
}
```

**Comment by Phoenix616** [comment]
Yeah, I'm not sure how much should be exposed directly in the click and what should just be gotten via the event like you wrote it. I personally just use the raw event itself for most special stuff, hence why it exists in the first place.

But yeah, the button/click type should probably be directly included.

Dou you think it should only show the button or all different click types like shift etc.

**Comment by stijnb1234** [comment]
For me left and right are enough. I think that catches most situations. The clicktype contains a method for isLeftClick and isRightClick.

**Comment by Phoenix616** [comment]
Actually I just noticed that [`Click#getType`](https://docs.phoenix616.dev/inventorygui/de/themoep/inventorygui/GuiElement.Click.html#getType()) which returns the `ClickType` enum that has `isLeftClick` and `isRightClick` methods is already implemented so I don't think any extra methods are necessary and I consider this already impemented.
