### ISSUE TITLE
Missing dependency jar file for latest build of version "1.6.1-SNAPSHOT"

### ISSUE THREAD

**Issue by MysticMight** [Phoenix616/InventoryGui#47]
### What is happening?

Error resolving dependency, see below for details and potential fix.

Building Process to reproduce:
1. Attempt to gradle build project with latest version "1.6.1-SNAPSHOT" and gradle equivalent dependency information, as given in README.md (Can provide if necessary, but doesn't seem relevant to issue as described in following).
2. Observe error resolving dependency (see log section).
Uncertain if this can be reproduced with maven similarly.

### What did you expect to happen?

Build as normal. Using version "1.6-SNAPSHOT" as a dependency instead resolves and builds successfully. Possibly a gradle issue that it doesn't allow using the previous build's jar file (uncertain if maven behaves the same or not).

It appears that the repo is missing the dependency jar file for latest build of version "1.6.1-SNAPSHOT", as can be seen in the repo at [1] and comparing the builds at [2]. E.g. latest build (#186) and #184 (last successful before latest)

Links (separate for readability):
[1] https://repo.minebench.de/de/themoep/inventorygui/1.6.1-SNAPSHOT/
[2] https://ci.minebench.de/job/InventoryGui/

### Version

1.6.1-SNAPSHOT

### Config

```YAML
No relevant config
```

### Server/system Version

unrelated

### Log

```shell
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find inventorygui-1.6.1-SNAPSHOT.jar (de.themoep:inventorygui:1.6.1-SNAPSHOT:20240216.131015-1).
     Searched in the following locations:
         https://repo.minebench.de/de/themoep/inventorygui/1.6.1-SNAPSHOT/inventorygui-1.6.1-20240216.131015-1.jar
```

### What other programs/plugins are you running?

Intellji IDEA and gradle (building issue)

**Comment by Phoenix616** [comment]
Should be fixed now. I forgot to setup the actual build when I changed things :see_no_evil: Make sure to clean the cache if it doesn't work directly.
