### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by FireML** [Phoenix616/InventoryGui#50]
### What is happening?

Using InventoryGui#show is throwing an IncompatibleClassChangeError:
https://pastes.dev/5MBUaEBzfv

This broke after I updated things to 1.21, it was working perfectly fine before.

### What did you expect to happen?

I expected the GUI to open as intended.

### Version

1.6.2-SNAPSHOT

### Config

```YAML
There is no config file.
```

### Server/system Version

[01:03:41 INFO]: This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Log

```shell
https://pastes.dev/NM5AM5zRdE
```

### What other programs/plugins are you running?

> pl
[01:04:16 INFO]: Server Plugins (11):
[01:04:16 INFO]: Paper Plugins:
[01:04:16 INFO]:  - DaisyLib, FireWarps, HuskTowns, TownyAddons
[01:04:16 INFO]: Bukkit Plugins:
[01:04:16 INFO]:  - CMI, CMILib, Denizen, Depenizen, EvenMoreFish, Jobs, Vault

**Comment by FireML** [comment]
The plugin throwing the error is using a paper-plugin.yml if that helps at all :slightly_smiling_face:

**Comment by Phoenix616** [comment]
That is an issue with your server software not correctly handling legacy code and needs to be fixed there.

For now either use a stable version (ideally 1.20.4. 1.20.6 should work to prevent this but can't be considered stable) or manually compile the library against 1.21.

**Comment by LOOHP** [comment]
InventoryView changed into an interface from an abstract class. Hence, if you compile your plugin on 1.21. It will not work on prior versions. However, SpigotMC will convert abstract class into interfaces at runtime so if you compile your plugin on 1.20.6, it will work on 1.21 as well.
For more information, see [this discussion](https://www.spigotmc.org/threads/inventoryview-changed-to-interface-backwards-compatibility.651754/).

**Comment by Phoenix616** [comment]
> InventoryView changed into an interface from an abstract class. Hence, if you compile your plugin on 1.21. It will not work on prior versions. However, SpigotMC will convert abstract class into interfaces at runtime so if you compile your plugin on 1.20.6, it will work on 1.21 as well.
> For more information, see [this discussion](https://www.spigotmc.org/threads/inventoryview-changed-to-interface-backwards-compatibility.651754/).

You have it the wrong way around: InventoryGui uses the old, abstract class (as it's compiled against the old API) and the server fails to rewrite it to the new version. Most likely a bug with Paper/Paper plugins as it works just fine on Spigot.

**Comment by FireML** [comment]
> That is an issue with your server software not correctly handling legacy code and needs to be fixed there as it basically breaks all old pugins doing simliar things.
> 
> For now either use a stable version (ideally 1.20.4. 1.20.6 should work to prevent this but can't be considered stable) or manually compile the library against 1.21.

got it. hopefully Paper fixes it soon :pray:
