### ISSUE TITLE
Duplication issue with bundles

### ISSUE THREAD

**Issue by FireML** [Phoenix616/InventoryGui#51]
### What is happening?

When using a GUIStorageElement, right clicking with a bundle will place the bundle in the GUI, but keep it on your cursor with one less item inside.

### What did you expect to happen?

I expected the item to be removed from the bundle like in a normal inventory.

### Version

1.6.3-SNAPSHOT

### Config

```YAML
N/A
```

### Server/system Version

This server is running Paper version 1.21.1-128-master@d348cb8 (2024-10-21T16:23:24Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Log

```shell
N/A
```

### What other programs/plugins are you running?

Nothing extra, just the plugin i used to test this.

### Additional context

https://youtu.be/FMg6mTQgNXg
A video showcasing the issue, provided by the person who found it.

**Comment by FireML** [comment]
I am aware bundles are currently experimental, however this will likely still be an issue when 1.21.2 releases.

**Comment by Phoenix616** [comment]
Thank you for the report! Please try to do report duplication bugs privately in the future e.g. via GitHub's security advisory system though :S

And it's unfortunately not easily possible to support that right now as there are no events for that specific behaviour so I had to block using them inside the storage slot for now. (And backwards compatibility might also get annoying :S)

Depending on how the API evolves I will look into supported that or recreating the functionality.

**Comment by FireML** [comment]
Yeah my bad, i'll keep that in mind for the future. Thanks for the quick fix :slightly_smiling_face:
